### PR TITLE
Fix for Matching the child segment in case the first segment is not available

### PR DESCRIPTION
**Pull request by mayurvaid-redvest**

### CODE REVIEW

**Comment by MikeEdgar** [comment]
Hi @mayurvaid-redvest , thank you for the pull request. It looks like this change breaks several of the tests (and is missing new tests of its own). Can you help me understand your use case for matching segments in a loop that is missing the start segment? It seems to be an atypical requirement.

**Comment by mayurvaid-redvest** [comment]
@MikeEdgar  , This is related to this open issue where first segment of the loop is missing and this code handles that 
 https://github.com/xlate/staedi/issues/357
Wanted to get your initial feedback ... We will work on test cases for sure

**Comment by mayurvaid-redvest** [comment]
> > This is related to this open requirement where first segment of the loop is missing and this code handles that
> 
> Understood on that part. Is your intent to tolerate that the first segment is missing and somehow process the transaction anyway? Or are you trying to still obtain validation information for the other segments?
> 
> Is this a common occurrence with your trading partner(s)? As I mentioned in #357 , invalid messages like that should be rejected, fixed by the trading partner, and re-sent.
> 
> My initial thought is that it isn't a situation that really should be supported in the validator, but I'm open to discussion if a good case can be made for it.

So Currently the tool that we support actually gives a proper error message saying first segment of the loop is missing , Whereas in our library we say it to be unexpected segment 

So Intention here is to irrespective start the loop on whichever segment is available in loop and proceed with the flow and send error message when required 

Let me know your thought is this makes sense

**Comment by MikeEdgar** [comment]
@mayurvaid-redvest , it makes sense, but there may be several complications -

1. Is it possible that the validator gets "lost" trying to identify where the child segment belongs?
2. How to avoid breaking existing users that expect this situation to raise the error(s) that are currently being raised.
3. What is the correct behavior when a child segment could belong to more than one loop? In this case, each loop would have started with a different segment, but the validator would need to guess which one is intended.
4. Situations where the unexpected segment could have been valid earlier in the current loop, but also in a child loop (i.e. segment not in proper order versus missing loop start segment).

Is your current tool used for viewing EDI files or for batch/online processing where an acknowledgement is generated? If generating an ACK, what error is used?

**Comment by mayurvaid-redvest** [comment]
> @mayurvaid-redvest , it makes sense, but there may be several complications -
> 
> 1. Is it possible that the validator gets "lost" trying to identify where the child segment belongs?
> 2. How to avoid breaking existing users that expect this situation to raise the error(s) that are currently being raised.
> 3. What is the correct behavior when a child segment could belong to more than one loop? In this case, each loop would have started with a different segment, but the validator would need to guess which one is intended.
> 4. Situations where the unexpected segment could have been valid earlier in the current loop, but also in a child loop (i.e. segment not in proper order versus missing loop start segment).
> 
> Is your current tool used for viewing EDI files or for batch/online processing where an acknowledgement is generated? If generating an ACK, what error is used?

1. Generally it won't as we are just moving to child elements of current 
2. What I feel is it should be good to this error coming out of fix rather than unexpected_segment , But if you think otherwise we can try fixing it out.
3. Since we are going over current elements child , It will  find if it exists for any of the child 
4. Segment not in order is valid scenario , But that will get caught in this right as cursor will not be able to find and continue to throw that error , This is just starting the loop and pointing to matched element if any found with respect to current element 

We are throwing missing mandatory segment error currently 

Let me know if response make sense

**Comment by MikeEdgar** [comment]
@mayurvaid-redvest , pardon the delayed response. I've been thinking about this scenario and I still do not think "missing mandatory segment" is the correct error. 

EDI standards declare that an instance of a loop only exists given the presence of the beginning segment (see X12.59, section 5.7). Without that segment, the segments that follow are still structurally part of the parent loop (or the transaction root). In that case, either the segment is out of order if it could have occurred earlier, or unexpected for the loop.

Assuming the presence of a loop without its beginning segment is atypical. Do you have any flexibility on changing the error reported in such a case? In either case the transaction is "junk" and should be rejected.

**Comment by MikeEdgar** [comment]
Closing this for now, see earlier comments for rationale. This may be revisited if there is a convincing argument to bypass the standards.

**Pull request closed without merging**
